
on: [pull_request, push]
#  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"



jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
#      with:
#        ref: '2.0-stable'

    - name: Install Remaining Prerequisites
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install python3-pip python3-setuptools
