on: [pull_request, push]
#  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Remaining Prerequisites
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get -qy update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -qy install python3-pip python3-setuptools

    - name: Building pandas
      run: |
        pip3 install --upgrade pip wheel setuptools
        pip3 install pandas
