on: [pull_request, push]
#  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Remaining Prerequisites
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get -qy update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -qy install python3-pip python3-setuptools python3-wheel python3.11-venv

    - name: Building numpy
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get -qy install libopenblas0 libopenblas-dev gfortran
        python3 -m venv numpy-venv
        source numpy-venv/bin/activate
        git clone https://github.com/numpy/numpy.git # TODO, submodule
        cd numpy
        git submodule update --init
        pip install -r test_requirements.txt
        CCACHE_DIR=/mnt/ccache PATH=/usr/lib/ccache:$PATH python3 setup.py build -j 4
        python3 setup.py bdist_wheel
        find .. -name \*.whl
        pwd

    - name: version
      run: echo "::set-output name=version::$( basename $(ls numpy/dist/*.whl) )"
      id: version

    - name: Uploads numpy whl package
      uses: actions/upload-artifact@v3
      with:
        #name: numpy
        name: ${{ steps.version.outputs.version }}
        path: numpy/dist/*.whl
        retention-days: 5

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        #release_name: ${{ steps.version.outputs.version }}
        release_name: Weekly build
        tag_name: ${{ github.ref }}
        #body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload numpy artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.version.outputs.version }}
        asset_name: ${{ steps.version.outputs.version }}
        #asset_content_type: application/zip

#    - name: Building pandas
#      run: |
#        python3 -m venv pandas-venv
#        source pandas-venv/bin/activate
#        pip3 install cython
#        git clone https://github.com/pandas-dev/pandas.git # TODO, submodule
#        cd pandas
#        python3 setup.py bdist_wheel
#        find ..
